import Phaser from 'phaser';
import './style.css';

type Fighter={body:Phaser.Physics.Arcade.Sprite;hp:number;speed:number;facing:number;attackUntil:number;hurtUntil:number;powerUntil:number;clones:HTMLElement[];kurama:boolean;visual:HTMLImageElement};
const W=960,H=540;const state={cd1:0,cd2:0,cd3:0,over:false};
const NARUTO_IMG='https://www.kindpng.com/picc/m/16-168001_naruto-sprite-mugen-freetoedit-naruto-pixel-art-png.png';
const GOKU_IMG='https://www.pngkey.com/png/full/114-1146726_goku-pixel-art-pixel-art-dragon-ball.png';
class FightScene extends Phaser.Scene{
 naruto!:Fighter;goku!:Fighter;keys!:Record<string,Phaser.Input.Keyboard.Key>;cursors!:Phaser.Types.Input.Keyboard.CursorKeys;ground!:Phaser.Physics.Arcade.StaticGroup;fx!:Phaser.GameObjects.Graphics;layer!:HTMLDivElement;aiTimer=0;
 constructor(){super('fight')}
 create(){this.cameras.main.setBackgroundColor('#10131f');this.add.rectangle(W/2,H/2,W,H,0x10131f);this.add.rectangle(W/2,410,W,220,0x20283a);for(let x=0;x<W;x+=80)this.add.line(0,0,x,420,x+40,540,0x34405b,.35).setOrigin(0);const tex=this.textures.createCanvas('pixel',8,8);if(tex){tex.context.fillStyle='#fff';tex.context.fillRect(0,0,8,8);tex.refresh()}this.ground=this.physics.add.staticGroup();const floor=this.add.rectangle(W/2,500,W,50,0x4a556f);this.physics.add.existing(floor,true);this.ground.add(floor);this.layer=document.createElement('div');this.layer.className='character-layer';document.body.appendChild(this.layer);this.naruto=this.makeFighter(250,430,NARUTO_IMG,'naruto-visual');this.goku=this.makeFighter(710,430,GOKU_IMG,'goku-visual');this.naruto.facing=1;this.goku.facing=-1;this.physics.add.collider(this.naruto.body,this.ground);this.physics.add.collider(this.goku.body,this.ground);this.keys=this.input.keyboard!.addKeys('A,S,ONE,TWO,THREE,R') as Record<string,Phaser.Input.Keyboard.Key>;this.cursors=this.input.keyboard!.createCursorKeys();this.fx=this.add.graphics();this.createHud();this.createTouchControls()}
 makeFighter(x:number,y:number,src:string,cls:string):Fighter{const body=this.physics.add.sprite(x,y,'pixel').setVisible(false).setSize(42,100).setOffset(3,0);body.setCollideWorldBounds(true);body.setDragX(900);body.setMaxVelocity(330,850);const img=document.createElement('img');img.src=src;img.className='fighter-visual '+cls+' idle';img.draggable=false;img.alt=cls;this.layer.appendChild(img);return{body,hp:100,speed:230,facing:1,attackUntil:0,hurtUntil:0,powerUntil:0,clones:[],kurama:false,visual:img}}
 createHud(){const el=document.createElement('div');el.className='hud';el.innerHTML='<div class="top"><div class="bar"><b>NARUTO</b><span id="nhp"></span></div><div class="title">NARUTO VS GOKU</div><div class="bar right"><b>GOKU</b><span id="ghp"></span></div></div><div class="powers"><span id="p1">1 RASENGAN</span><span id="p2">2 KAGEBUNSHIN</span><span id="p3">3 KURAMA</span></div><div id="msg" class="msg"></div>';document.body.appendChild(el)}
 createTouchControls(){const root=document.createElement('div');root.className='controls';root.innerHTML='<div class="left-controls"><button data-key="left">◀</button><button data-key="right">▶</button><button class="jump" data-key="jump">JUMP</button></div><div class="right-controls"><button data-key="A">A<br><small>PUNCH</small></button><button data-key="S">S<br><small>KICK</small></button><button class="restart" data-key="R">R<br><small>RESTART</small></button></div><div class="power-controls"><button data-key="1">1</button><button data-key="2">2</button><button data-key="3">3</button></div>';document.body.appendChild(root);root.querySelectorAll('button').forEach(b=>{const k=(b as HTMLElement).dataset.key!;const down=(e:Event)=>{e.preventDefault();this.touch(k,true)};const up=(e:Event)=>{e.preventDefault();this.touch(k,false)};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('pointerleave',up)})}
 touch(k:string,v:boolean){(this as any).touches??={};(this as any).touches[k]=v;if(v&&['A','S'].includes(k))this.attack(k);if(v&&['1','2','3'].includes(k))this.power(+k);if(v&&k==='jump')this.jump(this.naruto);if(v&&k==='R')this.restart()}
 pressed(k:string){return!!(this as any).touches?.[k]||!!this.keys[k]?.isDown}
 restart(){state.cd1=state.cd2=state.cd3=0;state.over=false;this.scene.restart()}
 jump(f:Fighter){if(f.body.body?.blocked.down)f.body.setVelocityY(-500)}
 attack(kind:string){const n=this.naruto,g=this.goku;n.attackUntil=this.time.now+300;n.visual.classList.add('attack');setTimeout(()=>n.visual.classList.remove('attack'),300);const reach=kind==='A'?85:100;if(Math.abs(n.body.x-g.body.x)<reach&&Math.abs(n.body.y-g.body.y)<100)this.hit(g,kind==='A'?8:11,n.facing*70)}
 hit(f:Fighter,dmg:number,kb:number){if(f.hurtUntil>this.time.now)return;f.hp=Math.max(0,f.hp-dmg);f.hurtUntil=this.time.now+220;f.body.setVelocity(kb,-180);f.visual.classList.add('hurt');setTimeout(()=>f.visual.classList.remove('hurt'),220)}
 power(num:number){const now=this.time.now;if(num===1&&now>=state.cd1){state.cd1=now+20000;this.naruto.powerUntil=now+900;const orb=this.add.circle(this.naruto.body.x+this.naruto.facing*50,this.naruto.body.y-65,25,0x55d9ff).setStrokeStyle(5,0xffffff);this.tweens.add({targets:orb,x:this.goku.body.x,y:this.goku.body.y-65,duration:350,onComplete:()=>{this.hit(this.goku,24,this.naruto.facing*180);orb.destroy()}})}if(num===2&&now>=state.cd2){state.cd2=now+10000;this.naruto.powerUntil=now+8000;this.spawnClones()}if(num===3&&now>=state.cd3){state.cd3=now+50000;this.naruto.powerUntil=now+25000;this.naruto.kurama=true;this.naruto.visual.classList.add('kurama');}}
 spawnClones(){this.naruto.clones.forEach(c=>c.remove());this.naruto.clones=[];for(let i=0;i<2;i++){const c=document.createElement('img');c.src=NARUTO_IMG;c.className='clone-visual';c.style.left=(50+(this.naruto.body.x+(i?60:-60)-W/2)/W*100)+'%';this.layer.appendChild(c);this.naruto.clones.push(c)}setTimeout(()=>{this.naruto.clones.forEach(c=>c.remove());this.naruto.clones=[]},8000)}
 ai(t:number){const g=this.goku,n=this.naruto,d=n.body.x-g.body.x;g.facing=d>0?1:-1;if(Math.abs(d)>95)g.body.setVelocityX(Math.sign(d)*125);else{g.body.setVelocityX(0);if(t>this.aiTimer){this.aiTimer=t+650;this.hit(n,Math.random()>.45?8:5,g.facing*45);g.visual.classList.add('attack');setTimeout(()=>g.visual.classList.remove('attack'),260)}}if(Math.random()<.004&&g.body.body?.blocked.down)this.jump(g)}
 update(t:number){if(Phaser.Input.Keyboard.JustDown(this.keys.R)){this.restart();return}if(state.over){this.updateVisuals();this.updateHud(t);return}const n=this.naruto;let dir=0;if(this.pressed('left')||this.cursors.left.isDown)dir--;if(this.pressed('right')||this.cursors.right.isDown)dir++;if(dir){n.body.setVelocityX(dir*n.speed);n.facing=dir}else n.body.setVelocityX(n.body.velocity.x*.8);if((this.cursors.up.isDown||this.pressed('jump'))&&n.body.body?.blocked.down)this.jump(n);if(Phaser.Input.Keyboard.JustDown(this.keys.A))this.attack('A');if(Phaser.Input.Keyboard.JustDown(this.keys.S))this.attack('S');if(Phaser.Input.Keyboard.JustDown(this.keys.ONE))this.power(1);if(Phaser.Input.Keyboard.JustDown(this.keys.TWO))this.power(2);if(Phaser.Input.Keyboard.JustDown(this.keys.THREE))this.power(3);this.ai(t);this.updateVisuals();this.updateFx(t);if(n.hp<=0||this.goku.hp<=0){state.over=true;(document.getElementById('msg')!).textContent=(n.hp>0?'NARUTO WINS!':'GOKU WINS!')+' • Press R or tap R to restart'}this.updateHud(t)}
 updateVisuals(){for(const f of [this.naruto,this.goku]){const x=f.body.x,y=f.body.y;f.visual.style.left=(x/W*100)+'%';f.visual.style.top=(y/H*100)+'%';f.visual.style.transform=`translate(-50%,-100%) scaleX(${f.facing})`;if(Math.abs(f.body.velocity.x)>20&&!f.visual.classList.contains('attack'))f.visual.classList.add('run');else f.visual.classList.remove('run')}}
 updateFx(t:number){this.fx.clear();const n=this.naruto;if(n.kurama&&n.powerUntil>t){this.fx.lineStyle(7,0xff7a18,.8);this.fx.strokeCircle(n.body.x,n.body.y-65,70+Math.sin(t/70)*7)}if(t>=state.cd3){n.kurama=false;n.visual.classList.remove('kurama')}}
 updateHud(t:number){const n=document.getElementById('nhp')!,g=document.getElementById('ghp')!;n.style.width=navigator?this.naruto.hp+'%':this.naruto.hp+'%';g.style.width=this.goku.hp+'%';const cd=(id:string,end:number)=>{const e=document.getElementById(id)!;const s=Math.max(0,(end-t)/1000);e.textContent=s>0?`${s.toFixed(1)}s`:'READY'};cd('p1',state.cd1);cd('p2',state.cd2);cd('p3',state.cd3)}}
const config:Phaser.Types.Core.GameConfig={type:Phaser.AUTO,width:W,height:H,parent:'game',physics:{default:'arcade',arcade:{gravity:{x:0,y:1000},debug:false}},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[FightScene],render:{antialias:true}};new Phaser.Game(config);