import Phaser from 'phaser';
import './style.css';

type Fighter={body:Phaser.Physics.Arcade.Sprite;hp:number;maxHp:number;speed:number;onGround:boolean;facing:number;attackUntil:number;hurtUntil:number;powerUntil:number;clones:Phaser.GameObjects.Graphics[];kurama:boolean};
const W=960,H=540;const gameState={cd1:0,cd2:0,cd3:0,roundOver:false};
class FightScene extends Phaser.Scene{
 naruto!:Fighter;goku!:Fighter;keys!:Record<string,Phaser.Input.Keyboard.Key>;cursors!:Phaser.Types.Input.Keyboard.CursorKeys;ground!:Phaser.Physics.Arcade.StaticGroup;fx!:Phaser.GameObjects.Graphics;hud!:Phaser.GameObjects.DOMElement;aiTimer=0;
 constructor(){super('fight')}
 create(){this.cameras.main.setBackgroundColor('#10131f');this.add.rectangle(W/2,H/2,W,H,0x10131f);this.add.rectangle(W/2,410,W,220,0x20283a);for(let x=0;x<W;x+=80)this.add.line(0,0,x,420,x+40,540,0x34405b,.35).setOrigin(0);const tex=this.textures.createCanvas('pixel',8,8);if(tex){tex.context.fillStyle='#fff';tex.context.fillRect(0,0,8,8);tex.refresh()}this.ground=this.physics.add.staticGroup();const floor=this.add.rectangle(W/2,500,W,50,0x4a556f);this.physics.add.existing(floor,true);this.ground.add(floor);this.naruto=this.makeFighter(250,430);this.goku=this.makeFighter(710,430);this.naruto.facing=1;this.goku.facing=-1;this.physics.add.collider(this.naruto.body,this.ground);this.physics.add.collider(this.goku.body,this.ground);this.keys=this.input.keyboard!.addKeys('A,S,ONE,TWO,THREE,R') as Record<string,Phaser.Input.Keyboard.Key>;this.cursors=this.input.keyboard!.createCursorKeys();this.fx=this.add.graphics();this.createHud();this.createTouchControls()}
 makeFighter(x:number,y:number):Fighter{const body=this.physics.add.sprite(x,y,'pixel').setVisible(false).setSize(42,100).setOffset(3,0);body.setCollideWorldBounds(true);body.setDragX(900);body.setMaxVelocity(330,850);return{body,hp:100,maxHp:100,speed:230,onGround:false,facing:1,attackUntil:0,hurtUntil:0,powerUntil:0,clones:[],kurama:false}}
 createHud(){const el=document.createElement('div');el.className='hud';el.innerHTML='<div class="top"><div class="bar"><b>NARUTO</b><span id="nhp"></span></div><div class="title">STICKMAN FIGHT</div><div class="bar right"><b>GOKU</b><span id="ghp"></span></div></div><div class="powers"><span id="p1">1 RASENGAN</span><span id="p2">2 KAGEBUNSHIN</span><span id="p3">3 KURAMA</span></div><div id="msg" class="msg"></div>';document.body.appendChild(el);this.hud=this.add.dom(0,0,el).setOrigin(0)}
 createTouchControls(){const root=document.createElement('div');root.className='controls';root.innerHTML='<div class="left-controls"><button data-key="left">◀</button><button data-key="right">▶</button><button class="jump" data-key="jump">JUMP</button></div><div class="right-controls"><button data-key="A">A<br><small>PUNCH</small></button><button data-key="S">S<br><small>KICK</small></button><button class="restart" data-key="R">R<br><small>RESTART</small></button></div><div class="power-controls"><button data-key="1">1</button><button data-key="2">2</button><button data-key="3">3</button></div>';document.body.appendChild(root);root.querySelectorAll('button').forEach(b=>{const k=(b as HTMLElement).dataset.key!;const down=(e:Event)=>{e.preventDefault();this.touch(k,true)};const up=(e:Event)=>{e.preventDefault();this.touch(k,false)};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('pointerleave',up)})}
 touch(k:string,v:boolean){(this as any).touches??={};(this as any).touches[k]=v;if(v&&['A','S'].includes(k))this.attack(k);if(v&&['1','2','3'].includes(k))this.power(Number(k));if(v&&k==='jump')this.jump(this.naruto);if(v&&k==='R')this.restart()}
 pressed(k:string){return!!(this as any).touches?.[k]||!!this.keys[k]?.isDown}
 restart(){gameState.cd1=gameState.cd2=gameState.cd3=0;gameState.roundOver=false;this.scene.restart()}
 update(t:number){if(Phaser.Input.Keyboard.JustDown(this.keys.R)){this.restart();return}if(gameState.roundOver){this.updateHud(t);return}const n=this.naruto,g=this.goku;let dir=0;if(this.pressed('left')||this.cursors.left.isDown)dir--;if(this.pressed('right')||this.cursors.right.isDown)dir++;if(dir){n.body.setVelocityX(dir*n.speed);n.facing=dir}if((this.cursors.up.isDown||this.pressed('jump'))&&n.body.body?.blocked.down)this.jump(n);if(Phaser.Input.Keyboard.JustDown(this.keys.A))this.attack('A');if(Phaser.Input.Keyboard.JustDown(this.keys.S))this.attack('S');if(Phaser.Input.Keyboard.JustDown(this.keys.ONE))this.power(1);if(Phaser.Input.Keyboard.JustDown(this.keys.TWO))this.power(2);if(Phaser.Input.Keyboard.JustDown(this.keys.THREE))this.power(3);this.ai(t);this.drawFighter(n,0xff7a21);this.drawFighter(g,0x4da6ff);this.updateFx(t);if(n.hp<=0||g.hp<=0){gameState.roundOver=true;(document.getElementById('msg')!).textContent=(n.hp>0?'NARUTO WINS!':'GOKU WINS!')+' • Press R or tap R to restart'}this.updateHud(t)}
 jump(f:Fighter){if(f.body.body?.blocked.down)f.body.setVelocityY(-500)}
 attack(kind:string){const n=this.naruto,g=this.goku;if(n.hurtUntil>this.time.now)return;n.attackUntil=this.time.now+260;const reach=kind==='A'?75:92,dmg=kind==='A'?7:10;if(Math.abs(n.body.x-g.body.x)<reach&&Math.abs(n.body.y-g.body.y)<90)this.hit(g,dmg,n.facing*40)}
 hit(f:Fighter,dmg:number,kb:number){if(f.hurtUntil>this.time.now)return;f.hp=Math.max(0,f.hp-dmg);f.hurtUntil=this.time.now+180;f.body.setVelocity(kb,-180)}
 ai(t:number){const g=this.goku,n=this.naruto,d=n.body.x-g.body.x;g.facing=d>0?1:-1;if(Math.abs(d)>90)g.body.setVelocityX(Math.sign(d)*125);else{g.body.setVelocityX(0);if(t>this.aiTimer){this.aiTimer=t+650;this.hit(n,Math.random()>.45?8:5,g.facing*45)}}if(Math.random()<.004&&g.body.body?.blocked.down)this.jump(g)}
 power(num:number){const now=this.time.now;if(num===1&&now>=gameState.cd1){gameState.cd1=now+20000;this.naruto.powerUntil=now+900;this.projectileRasengan()}if(num===2&&now>=gameState.cd2){gameState.cd2=now+10000;this.naruto.powerUntil=now+8000;this.spawnClones()}if(num===3&&now>=gameState.cd3){gameState.cd3=now+50000;this.naruto.powerUntil=now+25000;this.naruto.kurama=true;this.addKuramaAura()}}
 projectileRasengan(){const n=this.naruto,g=this.goku,orb=this.add.circle(n.body.x+n.facing*45,n.body.y-45,22,0x65d9ff).setStrokeStyle(5,0xffffff);this.tweens.add({targets:orb,x:g.body.x,y:g.body.y-35,duration:350,onComplete:()=>{if(Math.abs(orb.x-g.body.x)<55)this.hit(g,22,n.facing*180);orb.destroy()}})}
 spawnClones(){this.naruto.clones.forEach(c=>c.destroy());this.naruto.clones=[];for(let i=0;i<2;i++){const c=this.add.graphics();c.x=this.naruto.body.x+(i?55:-55);c.y=this.naruto.body.y;this.naruto.clones.push(c)}}
 addKuramaAura(){this.tweens.add({targets:this.naruto.body,scaleX:1.18,scaleY:1.12,duration:300,yoyo:true,repeat:8})}
 updateFx(t:number){this.fx.clear();const n=this.naruto;if(n.powerUntil>t&&n.kurama){this.fx.lineStyle(5,0xff5a18,.75);this.fx.strokeCircle(n.body.x,n.body.y-45,65+Math.sin(t/80)*5)}if(n.clones.length){n.clones.forEach((c,i)=>{if(t<n.powerUntil){c.clear();c.lineStyle(5,0xff7a21);c.strokeCircle(c.x,c.y-65,18);c.lineBetween(c.x,c.y-45,c.x,c.y-5);c.lineBetween(c.x,c.y-35,c.x+(i?30:-30),c.y-15);c.lineBetween(c.x,c.y-5,c.x+(i?20:-20),c.y+30)}else c.destroy()});if(t>=n.powerUntil)n.clones=[]}if(t>=gameState.cd3)n.kurama=false}
 drawFighter(f:Fighter,skin:number){const g=this.fx,x=f.body.x,y=f.body.y;g.lineStyle(7,skin,1);g.strokeCircle(x,y-72,18);g.lineBetween(x,y-54,x,y-5);const attacking=f.attackUntil>this.time.now;g.lineBetween(x,y-45,x+(attacking?f.facing*48:f.facing*25),y-25);g.lineBetween(x,y-43,x-f.facing*22,y-22);g.lineBetween(x,y-5,x-22,y+35);g.lineBetween(x,y-5,x+22,y+35);if(f===this.naruto&&f.kurama){g.lineStyle(3,0xffb52e,.9);g.strokeCircle(x,y-42,38)}}
 updateHud(t:number){const n=document.getElementById('nhp')!,g=document.getElementById('ghp')!;n.style.width=this.naruto.hp+'%';g.style.width=this.goku.hp+'%';const cd=(id:string,end:number)=>{const e=document.getElementById(id)!;const s=Math.max(0,(end-t)/1000);e.textContent=s>0?`${s.toFixed(1)}s`:'READY'};cd('p1',gameState.cd1);cd('p2',gameState.cd2);cd('p3',gameState.cd3)}}
const config:Phaser.Types.Core.GameConfig={type:Phaser.AUTO,width:W,height:H,parent:'game',physics:{default:'arcade',arcade:{gravity:{x:0,y:1000},debug:false}},dom:{createContainer:true},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[FightScene],render:{pixelArt:false,antialias:true}};new Phaser.Game(config);